apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: csi-ebs-node
  namespace: kube-system
  labels:
    app.kubernetes.io/name: csi-ebs-node
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: csi-ebs-node
  template:
    metadata:
      labels:
        app.kubernetes.io/name: csi-ebs-node
    spec:
      dnsPolicy: ClusterFirstWithHostNet
      nodeSelector:
        kubernetes.io/os: linux
      serviceAccountName: csi-ebs
      priorityClassName: system-node-critical
      tolerations:
        - operator: Exists
      volumes:
        - hostPath:
            path: /var/lib/kubelet/plugins/ebs.csi.volcengine.com
            type: DirectoryOrCreate
          name: socket-dir
        - hostPath:
            path: /var/lib/kubelet/
            type: DirectoryOrCreate
          name: mountpoint-dir
        - hostPath:
            path: /var/lib/kubelet/plugins_registry/
            type: DirectoryOrCreate
          name: registration-dir
        - hostPath:
            path: /dev
            type: Directory
          name: device-dir
      containers:
        - name: liveness-probe
          image: open-registry-cn-beijing.cr.volces.com/vke/livenessprobe:v2.6.0
          imagePullPolicy: Always
          args:
            - "--csi-address=/csi/csi.sock"
            - "--probe-timeout=3s"
            - "--v=2"
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
          resources:
            limits:
              cpu: 100m
              memory: 100Mi
            requests:
              cpu: 10m
              memory: 20Mi
        - name: node-driver-registrar
          image: open-registry-cn-beijing.cr.volces.com/vke/csi-node-driver-registrar:v2.5.1
          imagePullPolicy: Always
          args:
            - "--csi-address=$(ADDRESS)"
            - "--kubelet-registration-path=$(DRIVER_REG_SOCK_PATH)"
            - "--v=2"
          lifecycle:
            preStop:
              exec:
                command:
                  - /bin/sh
                  - -c
                  - rm -rf /registration/ebs.csi.volcengine.com-reg.sock /csi/csi.sock
          env:
            - name: "ADDRESS"
              value: "/csi/csi.sock"
            - name: "DRIVER_REG_SOCK_PATH"
              value: "/var/lib/kubelet/plugins/ebs.csi.volcengine.com/csi.sock"
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
            - name: registration-dir
              mountPath: /registration
          resources:
            limits:
              cpu: 100m
              memory: 100Mi
            requests:
              cpu: 10m
              memory: 20Mi
        - name: csi-ebs-driver
          image: open-registry-cn-beijing.cr.volces.com/vke/ebsplugin:v2.10
          imagePullPolicy: Always
          args:
            - "--endpoint=$(CSI_ENDPOINT)"
          ports:
            - containerPort: 9808
              name: healthz
              protocol: TCP
          livenessProbe:
            failureThreshold: 5
            httpGet:
              path: /healthz
              port: healthz
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 10
          env:
            - name: "CSI_ENDPOINT"
              value: unix:///csi/csi.sock
            - name: "VOLC_HOST"
              value: "open.volcengineapi.com"
            - name: "VOLC_ACCESSKEYID"
              value: "volc-akxxxxxxxxxxxxxxxxx"
            - name: "VOLC_SECRETACCESSKEY"
              value: "volc-skxxxxxxxxxxxxxxxxx"
          securityContext:
            privileged: true
          volumeMounts:
            - mountPath: /csi
              name: socket-dir
            - mountPath: /var/lib/kubelet/
              mountPropagation: Bidirectional
              name: mountpoint-dir
            - mountPath: /dev
              name: device-dir
          resources:
            limits:
              cpu: 200m
              memory: 200Mi
            requests:
              cpu: 10m
              memory: 20Mi