---
kind: Pod
apiVersion: v1
metadata:
  name: csi-pod
spec:
  containers:
    - name: csi-pod
      image: nginx
      command:
        - "/bin/bash"
        - "-c"
        - set -euo pipefail; while true; do echo $(hostname) $(date) >> /var/lib/www/$(hostname); sleep 1; done
      volumeMounts:
        - mountPath: "/var/lib/www"
          name: csi-tos-pvc
  volumes:
    - name: csi-tos-pvc
      persistentVolumeClaim:
        claimName: csi-tos-pvc