apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: csi-tos-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  # You can specify the pv name manually or just let kubernetes to bind the pv and pvc.
  volumeName: pv-tos
  # Currently tos only supports static provisioning, the StorageClass name should be empty.
  storageClassName: ""